### ISSUE TITLE
Running into an error, need help

### ISSUE THREAD

**Issue by sage-grey-voorhees** [SES-5215-F2020/svoorhees-quant#3]
Hello! 

Im running into the following error message:

 Error in select(., HINCP, race_ethnicity, JWMNP_binned, NP, PUMA, development, : unused arguments (HINCP, race_ethnicity, JWMNP_binned, NP, PUMA, development, AGEP, BLD_label, PINCP)

Its happening in all my past assignment select functions as well. So I think there is something wrong with R Studio or my packages. But I' really at a loss. 

https://github.com/SES-5215-F2020/svoorhees-quant/commit/a1ef25ea576c1bf4cfec0039b4923f87c862a419

**Comment by sage-grey-voorhees** [comment]
https://github.com/SES-5215-F2020/svoorhees-quant/commit/a1ef25ea576c1bf4cfec0039b4923f87c862a419

**Comment by c-voulgaris** [comment]
I can’t look at this closely right, right now because I’m away from my computer, but try using dplyr::select()

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sage-grey-voorhees** [comment]
Amazing. That worked! 

Thank you so much!
